export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
      <main className="">
        <h1 className="container p-6 text-3xl">
          Pdf from html by pPTR
        </h1>
      </main>
    </>

  )
}
